use libc;
use crate::codegen::CodeBuffer;

pub fn execute(buf: &CodeBuffer) -> i32 {
    let code = &buf.bytes;
    let len = code.len();

    unsafe {
        // Step 1: ask the OS for executable memory
        // mmap gives us a raw pointer to a chunk of memory
        // MAP_ANON  = not backed by a file, just empty memory
        // MAP_PRIVATE = only we can see it
        // PROT_READ | PROT_WRITE | PROT_EXEC = we can read, write, AND run it
        let ptr = libc::mmap(
            std::ptr::null_mut(),           // let OS pick the address
            len,                            // how many bytes we need
            libc::PROT_READ | libc::PROT_WRITE | libc::PROT_EXEC,
            libc::MAP_ANON | libc::MAP_PRIVATE,
            -1,                             // no file descriptor (MAP_ANON)
            0,                              // offset
        );

        if ptr == libc::MAP_FAILED {
            panic!("mmap failed");
        }

        // Step 2: copy our generated bytes into that memory
        std::ptr::copy_nonoverlapping(code.as_ptr(), ptr as *mut u8, len);

        // Step 3: cast the pointer to a function and call it
        // fn() -> i32 means: a function that takes no args and returns an i32
        let func: fn() -> i32 = std::mem::transmute(ptr);
        let result = func();

        // Step 4: give the memory back to the OS
        libc::munmap(ptr, len);

        result
    }
}
